### ISSUE TITLE
Need help with obtaining the bit width assigned to each layer.

### ISSUE THREAD

**Issue by Ahmad-Jarrar** [deJQK/FracBits#3]
I am trying to run your code and will be using your work in an academic project. I ran this experiment but I couldn't see any way provided to get which layers were assigned what bitwidth. 

How can I get the bitwidths for each layer in the network, similar to the data used to create figure 2 in the paper (attached below)?
<img width="572" alt="image" src="https://user-images.githubusercontent.com/34808778/208074020-18058f1e-cbab-43c0-9646-9769895796e1.png">

**Comment by deJQK** [comment]
`lamda_w` and `lamda_a` from each layer rounded and plotted against the layer index.

**Comment by Ahmad-Jarrar** [comment]
Thanks
